apiVersion: v1
kind: Service
metadata:
  name: {{ include "inlets-http-server.fullname" . }}
  labels:
    {{- include "inlets-http-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.controlPlane.port }}
    name: control-plane
    protocol: TCP
    targetPort: {{ .Values.controlPlane.port }}
  - port: {{ .Values.dataPlane.port }}
    name: data-plane
    protocol: TCP
    targetPort: {{ .Values.dataPlane.port }}
  selector:
    {{- include "inlets-http-server.selectorLabels" . | nindent 4 }}
