---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-client
  template:
    metadata:
      labels:
        app: inlets-client
    spec:
      containers:
      - name: inlets-client
        image: ghcr.io/inlets/inlets-pro:0.8.1
        imagePullPolicy: IfNotPresent
        command: ["inlets-pro"]
        args:
        - "client"
        - "--url=wss://EXIT_NODE_IP:8123/connect"
        - "--ports=80,443"
        - "--token=AUTH_TOKEN_HERE"
        - "--license=LICENSE_JWT_HERE"
        - "--upstream=SERVICE_NAME_HERE"
---
